### ISSUE TITLE
我觉得tea文件encrypt兼容python3,但是decrypt却不兼容python3

### ISSUE THREAD

**Issue by chengshuyi** [gera2ld/qqlib#7]
> ord函数对于python3来说是多余的

``` python
40            #print(prePlain[0])
Traceback (most recent call last):
  File "D:\workspace\python\QQ\deleteQQnews\tea.py", line 156, in <module>
    print(decrypt(a2b_hex(data),a2b_hex(randomTea)))
  File "D:\workspace\python\QQ\deleteQQnews\tea.py", line 120, in decrypt
    pos = ord(prePlain[0]) & 0x07 + 2
TypeError: ord() expected string of length 1, but int found
```

**Comment by gera2ld** [comment]
之前没用上`decrypt`，所以没注意。。。现在加了个测试，应该是真的兼容Python2和3了。。
